### ISSUE TITLE
lack of documents

### ISSUE THREAD

**Issue by AndyHon** [fjchange/object_centric_VAD#1]
Can you upload complete files and programs in object_detection folder?I would appreciate it very much.

**Comment by fjchange** [comment]
I have uploaded the files now, and modified some code in train.py and test.py . The object_detection is borrowed from tensorflow/models. @AndyHon

**Comment by AndyHon** [comment]
@fjchange Thanks for your timely reply. There should be “mscoco_label_map.pbtxt” label file in folder object_detection/data/，Could you please upload it, thank you.

**Comment by AndyHon** [comment]
In inference.py: the line of 159
> `np_paths_boxes_path = '/home/'+args.machine+'/'+args.dataset+'_'+'img_path_box.npy'`
args.machine shuold be delete
if dataset is avenue, But I don't know what 'img_path_box.npy' is. Could you tell me how to get this file? I'm sorry to bother you so many times.

**Comment by fjchange** [comment]
The file have been uploaded. The file_path is set machine related ( I train it in different servers )
I will update the code to make it independence.

**Comment by AndyHon** [comment]
@fjchange 
from object_detection.core import standard_fields as fields
Thanks for the update,but object_detection file should lack of "core" file

**Comment by AndyHon** [comment]
object_detection.utils import static_shape
object_detection.utils file should lack static_shape.py file
Thank you for constantly updating the content. Could you please run the experiment again to see what files or codes are missing in the whole document? Then upload your project in its entirety.
thank you very much.

**Comment by AndyHon** [comment]
Hello, do you have time to upload the missing code?

**Comment by fjchange** [comment]
Code should be completed now.

**Comment by AndyHon** [comment]
`from ._conv import register_converters as _register_converters
Traceback (most recent call last):
    File "/media/fxc/KESU/object_centric_VAD/scripts/inference.py", line 9, in <module>
    from object_detection.utils import visualization_utils as vis_util
    File "../object_detection/utils/visualization_utils.py", line 42, in <module>
    from object_detection.utils import shape_utils
    File "../object_detection/utils/shape_utils.py", line 25, in <module>
    from object_detection.utils import static_shape
ImportError: cannot import name 'static_shape'`
@fjchange Sorry to bother you again. You should be lack a file static_shape.py in /object_detection/ utils
