### ISSUE TITLE
excessive memory usage when training svm

### ISSUE THREAD

**Issue by xiadingZ** [fjchange/object_centric_VAD#3]
I implement in pytorch and  follow your settings and get 61.9 auc on shanghaitech, using only rgb. can you show your auc of it?
If I use three-stream, training of svm will terminate because of excessive memory usage, on my server. I use pytorch's  torchvision fasterrcnn_resnet50_fpn model to detect object, what's your number of objects on shanghaitech?
Thanks very much

**Comment by fjchange** [comment]
I don't know what is your training param setting, but mine is showed on #2 .
The features is too large to saved in  .m with scipy.io for ShanghaiTech dataset, so I haven't use it to train on matlab.
The number of objects I got on ShanghaiTech is about 190000.

**Comment by xiadingZ** [comment]
I follow your step but auc on shanghaitech is only 63. use default parameters. 
maybe your new changes on test.py cause this bug?
